---
functional:
  - Пользователь должен иметь возможность регистрации и авторизации #Двойное требование. Два теста, но фунцкионал один. Разбить?
  - Оба игрока должны видеть друг у друга редактор с кодом, вывод тестов, иметь возможность менять язык программирования во время решения #Тоже разбить на два требования?
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
non-functional:
  - Сайт должен быть удобным на мобильном устройстве #Размытая формулировка. Отредактировать или перенести в неявные?
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
