---
functional:
  - требование 1
  - требование 2
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - требование 6
